### ISSUE TITLE
Failing third row from a build

### ISSUE THREAD

**Issue by ramonpoca** [westfoxtrot/cyclops_pcb#2]
Hi, that's not a bug, just a request for hints.
I finally could flash my Cyclops board via SPI and have response from the system, except that the ROW3 (4th row) wouldn't register.
All traces look ok, there is connectivity with the ATMEGA pin. I've even tried to change the firmware to use another pin and run a jump wire, but no response.

Any hints? Next on my list is replacing the ATMEGA. 
Thanks!

**Comment by westfoxtrot** [comment]
Hello,

Someone had a similar problem and it turned out to be a firmware issue. Did you try to flash the latest firmware from qmk?

**Comment by ramonpoca** [comment]
Nay, I replaced the ATMEGA and it worked. I might have fried some pins (It's my first SMD soldering rodeo) 😄
